---
# Setting up docker on the VMs
- name: Install dependencies
  become: true
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'python-setuptools', 'software-properties-common']
    state: latest

- name: Add Docker repo key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  tags: 'docker'
  become: true
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker
  tags: 'docker'
  become: true
  apt:
    name: ['docker-ce']
    state: latest