---
# Creating all instances of the the VMs
- hosts: localhost
  gather_facts: true
  roles:
    - role: volume
    - role: security
    - role: instance

# Installing docker on all nodes
- hosts: total
  vars_files:
    - host_vars/var_name.yaml
  gather_facts: true
  roles:
    - role: config
    - role: installDocker

# Install couchDB for the database nodes
- hosts: database
  vars_files:
    - host_vars/var_name.yaml
  gather_facts: true
  roles:
    - role: installCouch
