- hosts: couchDB1, couchDB2
  become: true
  tasks:
    - name: Install pip
      become: yes
      ansible.builtin.apt:
        name: ["python3-dev", "python3-setuptools", "python3-pip"]
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

# - hosts: all
#   become: yes
#   tasks:
#     - name: sendDockerFile
#       ansible.builtin.copy:
#         src:  inventory.txt
#         dest: /data