---
# Enabling the cluster across all worker nodes
- name: enabling a cluster on worker nodes
  become: true
  command: curl -XPOST "http{{':'}}//{{couchdb_user}}{{':'}}{{couchdb_pass}}@{{item}}{{':'}}5984/_cluster_setup" \
                --header "Content-Type{{':'}}application/json" --data "{\"action\"{{':'}} \"remote_node\"{{':'}} \"{{ item }}\"\
                \"remote_current_user\":\"{{ couchdb_user }}\", \"remote_current_password\":\"{{ couchdb_pass }}\"\
                \"enable_cluster\", \"bind_address\"{{':'}}\"0.0.0.0\", \"username\"{{':'}} \ {{couchdb_user}},\
                \"password\"{{':'}}{{couchdb_pass}}, \"port\"{{':'}}\"5984\", \"node_count\"{{':'}}\"{{ groups['database'] | length }}\"}"
  loop: "{{ groups['workers'] }}"

# Adding nodes to the cluster
- name: adding nodes
  become: true
  command: curl -XPOST "http{{':'}}//{{couchdb_user}}{{':'}}{{couchdb_pass}}@{{item}}{{':'}}5984/_cluster_setup"\
                --header "Content-Type{{':'}} application/json" --data "{\"action\"{{':'}} \"add_node\", \"host\"{{':'}}\"{{item}}\",\
                \"port\"{{':'}} \"5984\", \"username\"{{':'}} \"{{couchdb_user}}\", \"password\"{{':'}}\"{{couchdb_pass}}\"}"
  loop: "{{ groups['workers'] }}"

# Finishing up the cluster setup
- name: finish cluster setup
  become: true
  command: curl -XPOST "http{{':'}}//{{couchdb_user}}{{':'}}{{couchdb_pass}}@{{item}}{{':'}}5984/_cluster_setup"\
                --header "Content-Type{{':'}} application/json" --data "{\"action\"{{':'}} \"finish_cluster\"}"
  loop: "{{ groups['masternode'] }}"
