---
# Install dependencies on the host
- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ["python3-dev", "python3-setuptools", "python3-pip"]
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  ansible.builtin.pip:
    name: ["pip", "openstacksdk"]
    state: latest

- name: make volume directory
  become: true
  command: mkdir /data

- name: Creating a filesystem (mkfs)
  become: true
  filesystem:
    fstype: ext4
    dev: "{{ item.device }}"
  loop: "{{ volumes }}"

- name: Mount volume onto the VM
  become: true
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.device }}"
    fstype: ext4
  loop: "{{ volumes }}"

